blank_issues_enabled: true

contact_links:
  - name: Discuss Sleep API
    url: https://discord.gg/w97qFff8n4
    about: You're welcome to join us on the Mathcord Discord server, we have a dedicated section.
